### ISSUE TITLE
converting failed

### ISSUE THREAD

**Issue by adriansuciu09** [ngageoint/geopackage-mbtiles-js#1]
I am trying to convert an MBTiles file to Geopackage in a Docker container. This is the Error i get.
![grafik](https://github.com/ngageoint/geopackage-mbtiles-js/assets/118290996/b885f8e6-5a02-48a0-abf3-9f0cdcf0ca5f)

**Comment by jclark118** [comment]
Node 18+ is not currently supported.  Node 16 is needed until the next round of updates.

**Comment by adriansuciu09** [comment]
it works if i install node 16 in my container. Thank you
